[APC-5625]: FIXUP: Change Request R2 short check

diff --git a/recipes-core/initscripts/files/imx8mp-irma6r2/factory-reset-functions b/recipes-core/initscripts/files/imx8mp-irma6r2/factory-reset-functions
--- a/recipes-core/initscripts/files/imx8mp-irma6r2/factory-reset-functions
+++ b/recipes-core/initscripts/files/imx8mp-irma6r2/factory-reset-functions
@@ -33,6 +33,8 @@ cable_diagnostic() {
     phytool write eth0/0x1/0x0017 0x1048 # Disbale link
     phytool write eth0/0x1/0x0012 0x0406 # Enable diagnostic clock
 
+    # The cable diagnostic might fail due to active link partner.
+    # Try harder if link partner is active.
     retries=5
     while [ "$retries" -gt 0 ]; do
         phytool write eth0/0x1:0x1E/0xBA1B 0x0001 # Run diagnostic
@@ -42,11 +44,11 @@ cable_diagnostic() {
         [ $((pair_a)) -ne 0 ] && [ $((pair_b)) -ne 0 ] && break
         retries=$((retries-1))
     done
-    [ "$retries" -gt 0 ] || return 1
 
     # Stop cable diagnostic and reset
-    phytool write eth0/0x1/0x0017 0x3048 # Enable link
     phytool write eth0/0x1/0x0012 0x0402 # Disable diagnostic clock
+    phytool write eth0/0x1/0x0017 0x3048 # Enable link
+    [ "$retries" -gt 0 ] || return 1
 
     echo "  A: $pair_a $(print_info "$pair_a")"
     echo "  B: $pair_b $(print_info "$pair_b")"
@@ -78,4 +80,5 @@ factory_reset() {
     rm -f /mnt/iris/counter/webserver/preferences.json
     rm -f /mnt/iris/counter/webserver/authentication.sqlite
     rm -f /mnt/iris/logging/*.sqlite
+    rm -f /mnt/iris/chrony/chrony.conf
 }
